// app/layout.js
import RootLayoutClient from "./RootLayoutClient";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <RootLayoutClient>
      {children}
    </RootLayoutClient>
  );
}
